### ISSUE TITLE
Nullable enums fail to be generated

### ISSUE THREAD

**Issue by abestel** [guardrail-dev/guardrail#1260]
I was trying to generate some code from an OpenAPI specification ([Github REST API](https://github.com/github/rest-api-description/blob/32b015fab19539c9a569ec876815333f277ede81/descriptions/api.github.com/api.github.com.yaml) that contains the following enum (I think this is where the issue lies):

```yml
    secret-scanning-alert-resolution:
      type: string
      description: "**Required when the `state` is `resolved`.** The reason for resolving
        the alert. Can be one of `false_positive`, `wont_fix`, `revoked`, or `used_in_tests`."
      nullable: true
      enum:
      - 
      - false_positive
      - wont_fix
      - revoked
      - used_in_tests
 ```

The generation failed with the following stacktrace:

```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at dev.guardrail.generators.syntax.package$RichString$.splitParts$extension(package.scala:52)
        at dev.guardrail.generators.syntax.package$RichString$.toPascalCase$extension(package.scala:58)
        at dev.guardrail.generators.ScalaGenerator$ScalaInterp$.formatEnumName(ScalaGenerator.scala:77)
        at dev.guardrail.generators.ScalaGenerator$ScalaInterp$.formatEnumName(ScalaGenerator.scala:30)
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromEnum$1(ProtocolGenerator.scala:153)
          ...
        at dev.guardrail.ProtocolGenerator$.validProg$1(ProtocolGenerator.scala:151)
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromEnum$36(ProtocolGenerator.scala:204)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromEnum$35(ProtocolGenerator.scala:204)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromEnum$33(ProtocolGenerator.scala:203)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromEnum$31(ProtocolGenerator.scala:202)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromEnum$30(ProtocolGenerator.scala:201)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.fromEnum(ProtocolGenerator.scala:200)
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromSwagger$9(ProtocolGenerator.scala:770)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromSwagger$8(ProtocolGenerator.scala:769)
        at dev.guardrail.core.HighPriorityTrackerSyntax$RefineSyntax$RefinePartiallyApplied.$anonfun$apply$4(Tracker.scala:105)
          ...
        at dev.guardrail.core.HighPriorityTrackerSyntax$RefineSyntax$RefinePartiallyApplied.apply(Tracker.scala:107)
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromSwagger$7(ProtocolGenerator.scala:767)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromSwagger$6(ProtocolGenerator.scala:763)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromSwagger$4(ProtocolGenerator.scala:762)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.$anonfun$fromSwagger$3(ProtocolGenerator.scala:761)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
        at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
          ...
        at dev.guardrail.ProtocolGenerator$.fromSwagger(ProtocolGenerator.scala:759)
        at dev.guardrail.Common$.prepareDefinitions(Common.scala:50)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$19(CoreTermInterp.scala:220)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$18(CoreTermInterp.scala:218)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$17(CoreTermInterp.scala:217)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$16(CoreTermInterp.scala:216)
        at dev.guardrail.ReadSwagger$.$anonfun$readSwagger$4(ReadSwagger.scala:25)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.ReadSwagger$.readSwagger(ReadSwagger.scala:25)
        at dev.guardrail.CLICommon.$anonfun$guardrailRunner$3(CLI.scala:169)
          ...
        at dev.guardrail.CLICommon.$anonfun$guardrailRunner$2(CLI.scala:166)
        at dev.guardrail.TargetValue.flatMap(Target.scala:101)
        at dev.guardrail.CLICommon.$anonfun$guardrailRunner$1(CLI.scala:166)
        at dev.guardrail.sbt.Tasks$.guardrailTask(Tasks.scala:36)
        at dev.guardrail.sbt.AbstractGuardrailPlugin.calcResult$1(AbstractCodegenPlugin.scala:180)
        at dev.guardrail.sbt.AbstractGuardrailPlugin.$anonfun$cachedGuardrailTask$3(AbstractCodegenPlugin.scala:187)
        at dev.guardrail.sbt.AbstractGuardrailPlugin.$anonfun$cachedGuardrailTask$3$adapted(AbstractCodegenPlugin.scala:185)
          ...
        at dev.guardrail.sbt.AbstractGuardrailPlugin.$anonfun$cachedGuardrailTask$2(AbstractCodegenPlugin.scala:197)
          ...
        at dev.guardrail.sbt.AbstractGuardrailPlugin.cachedGuardrailTask(AbstractCodegenPlugin.scala:200)
        at dev.guardrail.sbt.AbstractGuardrailPlugin.$anonfun$scopedSettings$2(AbstractCodegenPlugin.scala:205)
          ...
```

The specification is OK considering the documentation about enums on [swagger.io](https://swagger.io/docs/specification/data-models/enums/).

I managed to reproduce it in integration tests by modifying `StringEnum` in `modules/sample/src/main/resources/enumerations.yaml` to:

```yml
    StringEnum:
      type: string
      nullable: true
      enum:
        -
        - v1
        - v2
        - i like spaces
```

I am really not certain of how to fix this issue, the code is very new to me and I don't really know where the nullability should be checked. If you give me some pointers and could work on a PR :-)

**Comment by blast-hardcheese** [comment]
Good find! I just merged #1213, which changes all the line numbers, so reproducing the error on current master using your modification to `enumerations.yaml` and running
```
sbt> cli --client --specPath modules/sample/src/main/resources/enumerations.yaml --outputPath modules/sample-akkaHttp/target/generated --packageName enumerations.client.akkaHttp --framework akka-http
```

yields
```
[info] Error: Error attempting to process modules/sample/src/main/resources/enumerations.yaml:
[info] java.lang.NullPointerException
[info]         at dev.guardrail.generators.syntax.package$RichString$.splitParts$extension(package.scala:52)
[info]         at dev.guardrail.generators.syntax.package$RichString$.toPascalCase$extension(package.scala:58)
[info]         at dev.guardrail.generators.scala.ScalaGenerator$ScalaInterp$.formatEnumName(ScalaGenerator.scala:78)
[info]         at dev.guardrail.generators.scala.ScalaGenerator$ScalaInterp$.formatEnumName(ScalaGenerator.scala:31)
[info]         at dev.guardrail.generators.ProtocolGenerator$.$anonfun$fromEnum$1(ProtocolGenerator.scala:93)
[info]           ...
[info]         at dev.guardrail.generators.ProtocolGenerator$.validProg$1(ProtocolGenerator.scala:91)
[info]         at dev.guardrail.generators.ProtocolGenerator$.$anonfun$fromEnum$36(ProtocolGenerator.scala:144)
[info]           ...
[info]         at dev.guardrail.generators.ProtocolGenerator$.$anonfun$fromEnum$35(ProtocolGenerator.scala:144)
[info]         at dev.guardrail.TargetValue.flatMap(Target.scala:101)
[info]         at dev.guardrail.Target$$anon$1.flatMap(Target.scala:36)
[info]         at dev.guardrail.Target$$anon$1.flatMap(Target.scala:27)
[info]           ...
```

[`dev.guardrail.generators.scala.ScalaGenerator$ScalaInterp$.formatEnumName(ScalaGenerator.scala:78)`](https://github.com/guardrail-dev/guardrail/blob/9d6dc144847e5bb67aaf631a373094d9800f7ae4/modules/scala-support/src/main/scala/dev/guardrail/generators/scala/ScalaGenerator.scala#L78) is injected using tagless-final style, used [here](https://github.com/guardrail-dev/guardrail/blob/9d6dc144847e5bb67aaf631a373094d9800f7ae4/modules/core/src/main/scala/dev/guardrail/generators/ProtocolGenerator.scala#L89-L93), suggesting that `StringHeldEnum` is being constructed with invalid values.
Searching for the constructor takes us [here](https://github.com/guardrail-dev/guardrail/blob/9d6dc144847e5bb67aaf631a373094d9800f7ae4/modules/core/src/main/scala/dev/guardrail/generators/SwaggerGenerator.scala#L61), where `StringHeldEnum.apply` is just used directly, without doing any validation on the enumeration values themselves.

I think `xs => StringHeldEnum(xs.flatMap(Option.apply))` should be sufficient, but please add a minimal reproduction case in [`RegressionTests.scala`](https://github.com/guardrail-dev/guardrail/blob/9d6dc144847e5bb67aaf631a373094d9800f7ae4/project/src/main/scala/RegressionTests.scala#L80) referencing this issue number.

Thanks for the report!

**Comment by abestel** [comment]
It took me longer than I expected to find time to work on this.
The PR is now open if you want to check it :-)
